name: Build Kivy APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git ayarları
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Sistem bağımlılıkları
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip curl

      - name: Python paketleri
        run: |
          pip install --break-system-packages cython
          pip install --break-system-packages appdirs colorama jinja2 "sh>=1.10,<2.0" build toml packaging setuptools
          pip install --break-system-packages buildozer

      - name: Android SDK araçlarını indir
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q sdk-tools.zip -d $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest

      - name: Android lisanslarını kabul et
        run: yes | sdkmanager --licenses
        env:
          PATH: $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH

      - name: APK üretimi
        run: buildozer android debug

      - name: APK'yı kaydet
        uses: actions/upload-artifact@v4
        with:
          name: depoapp-debug.apk
          path: bin/*.apk
