name: Build Kivy APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Git kurulumu
        run: |
          sudo apt update
          sudo apt install -y git

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Buildozer kurulumu
        run: |
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer

      - name: APK üretimi
        run: |
          buildozer init || true
          buildozer android debug

      - name: APK'yı kaydet
        uses: actions/upload-artifact@v4
        with:
          name: depoapp-debug.apk
          path: bin/*.apk
