name: Docker Buildozer APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Docker kurulumu
        uses: docker/setup-buildx-action@v2

      - name: Docker ile APK üretimi
        run: |
          docker build -t kivy-apk .
          mkdir -p bin
          docker run --rm -v ${{ github.workspace }}/bin:/app/bin kivy-apk

      - name: APK'yı kaydet
        uses: actions/upload-artifact@v4
        with:
          name: depoapp-debug.apk
          path: bin/*.apk
